---
- hosts: localhost
  roles:
    - role: cyberark.conjur-lookup-plugin
  vars:
    username_value: "{{ lookup('retrieve_conjur_variable', 'AAM_Vault/ansible/DevOps_Safe/ip-192-168-20-63.ec2.internal/username') }}"
    key_value: "{{ lookup('retrieve_conjur_variable', 'AAM_Vault/ansible/DevOps_Safe/ip-192-168-20-63.ec2.internal/password') }}"
        
  tasks: 
    - name: Initiate TempFile Module for SSH Private Key
      tempfile:
        state: file
        suffix: key
      register: temp_key
      no_log: no

    - name: Write SSH Private Key to TempFile
      copy:
        dest: "{{ temp_key.path }}"
        content: "{{ key_value }}"
      delegate_to: localhost
      changed_when: false
      no_log: no
      
    - name: Set Username and SSH Private Key TempFile to a Fact
      set_fact:
        cyberark_username: "{{ username_value }}"
        cyberark_ssh_privatekey: "{{ temp_key.path }}"
      no_log: no

- hosts: servers
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_user: "{{ hostvars['localhost']['cyberark_username'] }}"
    ansible_ssh_private_key_file: "{{ hostvars['localhost']['cyberark_ssh_privatekey'] }}"
  roles:
    - role: cyberark.conjur-host-identity
      conjur_appliance_url: "{{ lookup('env','CONJUR_APPLIANCE_URL') }}"
      conjur_account: "{{ lookup('env','CONJUR_ACCOUNT') }}"
      conjur_host_factory_token: "{{ lookup('env','CONJUR_HF_TOKEN') }}"
      conjur_host_name: "{{inventory_hostname}}"
      conjur_validate_certs: false
      conjur_ssl_certificate: "{{lookup('env', 'CONJUR_CERT_FILE')}}"
